logging:
  level:
    root: INFO
    com.example.demo: TRACE

server:
  port: 8080

spring:
  application:
    name: demo-gateway

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:13306/micro-stack
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      dialect: org.hibernate.community.dialect.MySQLDialect
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  liquibase:
    changeLog: classpath:db/db.changelog-master.yml

security:
  jwt:
    secretKey: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expirationMs: 86400000
