name: micro-stack

services:
  mysql:
    image: mysql:8.4
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=micro-stack
    ports:
      - 13306:3306
  redis:
    image: redis:8.0
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    hostname: mail.example.com
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
  consul-server:
    image: hashicorp/consul:1.21
    ports:
      - 8300:8300/tcp
      - 8500:8500/tcp
      - 8600:8600/tcp
      - 8600:8600/udp
    command: consul agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0 -data-dir=/consul/data
#  kafka:
#    image: apache/kafka:latest
#    ports:
#      - 9092:9092
